# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8324d891399eb17fb616bccc05e333d7"
name = "PointPlus Pro"
handle = "pointplus-pro"
application_url = "https://surgical-wax-visitors-poet.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bf95f64d.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://surgical-wax-visitors-poet.trycloudflare.com/auth/callback",
  "https://surgical-wax-visitors-poet.trycloudflare.com/auth/shopify/callback",
  "https://surgical-wax-visitors-poet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
